### ISSUE TITLE
Disable saved search notification interval UI

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#398] opened 2024-04-01 19:39 UTC
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6367454523

---

**Issue 1**

The module `search_api_saved_searches` now shows a field where I can select an interval to receive notifications to changes to my search results.

At first I thought this was a new feature, however the settings for it are on prod and there hasn't been a build in a while, so it doesn't seem to be new. We don't use this feature, we have a more robust way of notifying users with updates going out for bookmarked records that have a major update.

**Issue 2**

When I try to save a search (logged in as admin) I try to save a search I loose the admin menu and I see the login link on the top right. When I go to a different page, I am logged in, but the search is not saved

To duplicate

1. log in as admin
2. go to the search page
3. search for a phrase
4. in the text box, name your search
5. save
6. see that you appear to be logged out, but still on the search page
7. go to any other page
8. go to dashboard
9. see that search you saved in steps 4 and 5 is not on the dashboard.

**Other info**

This problem was first found on April 1. I noticed it in ddev after importing the db from dv14. I checked dv14 and the issues shows there as well.

## to do
- [x] Remove option to select saved search update interval on the search page
- [x] Searches can be saved

screenshot

<img width="686" alt="image" src="https://github.com/bcgov/MFIN-Data-Catalogue/assets/3910508/00ec4f2b-b7b7-4158-8c1c-a29c39c62541">

**Comment by CraigClark** [comment] 2024-04-02 13:55
@lkmorlan Not sure if it matters, but in ddev, when I `drush cex`, it want's to export config for `core.entity_form_display.search_api_saved_search.default.default`, I wasn't working on that at all

**Comment by lkmorlan** [comment] 2024-04-02 15:42
Notification interval UI disabled.

Unable to reproduce the problem with saving searches.

**Comment by NicoledeGreef** [comment] 2024-04-02 18:16
See related #400 . Closing this ticket.

**Closed as completed by NicoledeGreef** 2024-04-02 18:16 UTC
Labels: bug, task, Sprint 15
