### ISSUE TITLE
Time out error when uploading replacement data dictionary

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#481] opened 2024-05-17 23:51 UTC
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6665272272

---

## Describe the bug
When uploading the attached data dictionary file ([ptt-transaction_ID_87_for_upload.csv](https://github.com/bcgov/MFIN-Data-Catalogue/files/15358841/ptt-transaction_ID_87_for_upload.csv)) the preview is displayed but the site times out when importing.

## To reproduce
Steps to reproduce the behaviour:
1. Go to https://cat.data.fin.gov.bc.ca/node/87/add-columns?destination=/node/87/build
2. Select a downloaded copy of attached file as the 'Import file'
3. Click on 'Upload'
4. Scroll down to and click 'Import'
5. See error

## Expected behaviour
The data should be loaded and replace the existing data dictionary.

## Screenshots

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/141185297/2d5c62c8-5416-4752-999f-93fc421ea185)

## Additional context

File: [ptt-transaction_ID_87_for_upload.csv](https://github.com/bcgov/MFIN-Data-Catalogue/files/15358841/ptt-transaction_ID_87_for_upload.csv)

**Comment by CraigClark** [comment] 2024-05-21 12:51
I tested this and I was able to duplicate the issue. On https://dev.cat.data.fin.gov.bc.ca/ I was able to successfully upload the same `.csv` file. This is most likely a resource issue. @NicoledeGreef , this is likely something for App Ops to look into.

**Comment by NicoledeGreef** [comment] 2024-05-22 16:28
Agreed- it was successful in dv14 as well so likely due to resource constraints in Production.

One thing to check could be PHP resources (maxTimeout, maxInput, etc.) but getting more OCP resource allocation quota would also help.

**Comment by NicoledeGreef** [comment] 2024-05-24 18:17
Email sent to App Ops/devs re: Tech Lead contacts for the project namespace in OCP and requesting assistance in putting in the Storage increase request.

**Comment by chrislaick** [comment] 2024-05-24 19:13
@NicoledeGreef I don't think this is a storage issue. ea352d-prod has 16GB storage quota, of which 9GB has been allocated as below. And you can take a look at the utilization of the 9GB: 
![Screenshot 2024-05-24 121219](https://github.com/bcgov/MFIN-Data-Catalogue/assets/99423089/f5e044cd-8724-4089-b8d3-a1188959ecc4)

This seems to be a PHP or server config issue with timing out.

**Comment by CraigClark** [comment] 2024-05-24 20:45
@NicoledeGreef I was talking to @sylus about this. He mentioned that last time we were having time outs, the solution was to  increase the cpu so it executed faster, however there isn't much room left to do that again.

Another thing App Ops can investigate is determining if the problem is on the PHP side or the DB

**Comment by chrislaick** [comment] 2024-05-24 21:38
@NicoledeGreef I'm going to put in a quota increase request for TEST and PROD to the next CPU bump, citing the need for more minimum 3 replicas in TEST and PROD. Once we get that approved, maybe we can increase CPU limits in the relevant pods to speed up the job. In the mean time, @sylus which pod/container would that be for us to increase CPU?

**Comment by NicoledeGreef** [comment] 2024-05-29 15:47
Platform Services sent this message in response to CPU increase request:

_Thank you for your recent request to increase the CPU quotas for your project. After a detailed review of the current resource utilization metrics in ea352d-test namespace, we have some important updates and recommendations._

_**Decision on the Quota Increase Request**
Based on our analysis, we have observed that the overall CPU utilization across your namespace is currently very low at 1.59%. Although there is significant CPU throttling in the PostgreSQL cluster nodes, this alone does not justify a broad increase in CPU quotas for all components of your application._

_**Recommendations for Resource Optimization**_
_**1.	Resource Optimization:** Before considering an increase in CPU quotas, we strongly recommend conducting a thorough tuning of your application’s resource usage. This includes optimizing the configuration and performance of the components that are experiencing high throttling, specifically the PostgreSQL nodes._
_**2.	Reduce Unused CPU Limits:** We recommend adjusting the CPU limits downwards for pods that are consistently using far less CPU than allocated. This adjustment will not only reduce resource wastage but also allow your Kubernetes cluster to allocate resources more efficiently. Lowering the CPU limits where possible will enable you to spin up more pods within the same resource quota, enhancing scalability and fault tolerance of your application without additional resource requests_
_**3.	Detailed Monitoring:** Please continue to monitor the CPU usage and throttling metrics closely. This will help you identify specific areas where adjustments are necessary and can lead to more efficient use of resources._
_**4.	Incremental Adjustments:** Consider making incremental adjustments to the CPU limits and requests for the specific pods that show high throttling rates.._

_**Further Guidance and Resources**
We encourage you to review the guidelines provided in the following documentation to better understand the process and best practices for requesting quota increases and managing resources effectively:_ [Request Quota Increase for OpenShift Project Set](https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/automation-and-resiliency/request-quota-increase-for-openshift-project-set/)

_**Conclusion**_
_At this time, we will hold off on approving an increase in CPU quotas. We believe that by implementing these optimizations and adjustments, you can achieve better performance and resource utilization within the current quotas. Please implement these recommendations and monitor the changes. If performance issues persist after these adjustments, we can revisit the discussion regarding additional resources._

**Comment by sylus** [comment] 2024-05-30 13:03
So the problem here was ultimately OpenShifts router, whenever a request takes more then 30secs HAProxy gives you that timeout and not Nginx / Varnish. Took a little bit to figure out but I increased the time at that level using an annotation.

See the M.R. associated. :)

**Comment by CraigClark** [comment] 2024-05-30 13:22
I tested this. I was able to upload the `.csv` @ChristaBull provided without issue to <https://cat.data.fin.gov.bc.ca/node/87> without issue.

when I upload a .`csv` with 1000, I get a time-out error on screen, but when I look at the node, they are all there <https://cat.data.fin.gov.bc.ca/node/205/edit?display=section_6&destination=/node/205/build>. This is similar to the behaviour we saw when importing the information schedule.

@NicoledeGreef , I left the test record on prod for you to take a look. It should be deleted.

I have attached a couple of large files you can do tests with. 
[extended_test_data_500.csv](https://github.com/bcgov/MFIN-Data-Catalogue/files/15500554/extended_test_data_500.csv)
[extended_test_data_1000.csv](https://github.com/bcgov/MFIN-Data-Catalogue/files/15500555/extended_test_data_1000.csv)

**Comment by CraigClark** [comment] 2024-05-30 14:30
Some more information on this

Will has set the HAProxy  to 60 seconds. What happens is HAProxy is timing out, but Drupal keeps working in the background. That's why we are seeing 504 but the import still happens.

Ideally the import should be optimized. Have it run in batches of 50 or so. This is a change to the application, not the environment it runs on

**Comment by CraigClark** [comment] 2024-05-30 19:13
Assigning to @lkmorlan  to see if we can get this to go in batches.

Liam, please document where Chris and/or Dan can change the batch size. They may want to adjust that.

**Comment by lkmorlan** [comment] 2024-05-31 19:02
The batch size can be adjusted in `admin/config/data-catalogue`.

**Comment by NicoledeGreef** [comment] 2024-05-31 22:46
Thanks @sylus @CraigClark @lkmorlan @chrislaick .

@ChristaBull  - larger column number imports should be OK now. Please try your imports and get in touch if there is any issue.

**Closed as completed by NicoledeGreef** 2024-05-31 22:46 UTC
Labels: bug, Priority: high, task, Sprint 18
