### ISSUE TITLE
Remove test tables from dev/test/prod

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#450] opened 2024-04-26 13:06 UTC
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6530774360

---

- [x] Create Drush command to remove test tables

**Comment by sylus** [comment] 2024-05-06 01:33
Hi @CraigClark this might be best for @lkmorlan I don't quite know the prefixes and I'm not sure what should be kept if any.

**Comment by CraigClark** [comment] 2024-05-06 13:18
Ok, I'll assign to @lkmorlan

**Comment by lkmorlan** [comment] 2024-05-06 16:43
Any table starting with `test` should be deleted.

This command will delete test tables. It is limited to 500 tables to prevent running out of memory. This is normally enough. I could make a Drush command that would run this, if that would be helpful. Or @sylus could configure things so that this gets run directly on the database when needed.

```
DO
$do$
BEGIN
	EXECUTE (
		SELECT 'DROP TABLE ' || string_agg(format('%I.%I', schemaname, tablename), ', ')
		FROM (
			SELECT * FROM pg_catalog.pg_tables t
			WHERE  schemaname NOT LIKE 'pg\_%'   -- exclude system schemas
			AND    tablename LIKE 'test' || '%'  -- your table name prefix
			LIMIT 500
		) sub
	);
END
$do$;
```

[Based on this post](https://stackoverflow.com/questions/27610890/drop-all-tables-sharing-the-same-prefix-in-postgres).

**Comment by sylus** [comment] 2024-05-23 16:10
I just manually ran this on all the environments and it removed all of the test tables.

Not sure if we want to make this a drush command or not but will leave this to @lkmorlan to decide.

**Comment by CraigClark** [comment] 2024-05-29 14:37
@lkmorlan Can I close this, or do you think there should be a drush command?

**Comment by lkmorlan** [comment] 2024-05-29 14:48
I am working on making a Drush command.

**Comment by CraigClark** [comment] 2024-05-29 14:53
@lkmorlan, perfect. When you are done, please add the command and any other necessary info to the [test plan wiki page](https://github.com/bcgov/MFIN-Data-Catalogue/wiki/Test-plan)

**Comment by NicoledeGreef** [comment] 2024-05-31 22:48
@chrislaick @danhgov  - can you please review the Drush command addition when you have an opportunity?

**Comment by danhgov** [comment] 2024-06-06 19:59
@NicoledeGreef, I had a look at @lkmorlan's code, and ran it on my localhost. I can confirm that it deleted all the test tables, and that the site still runs without them.

Would you like me to go ahead and run it on dev/test/prod? I'll start with just dev (and maybe test), and let you know when it's done so that you can confirm 100% it is working, before we procede to run it on prod.

**Comment by NicoledeGreef** [comment] 2024-06-10 17:59
Please proceed @danhgov

**Comment by danhgov** [comment] 2024-06-11 17:55
It seems to me that these tables have already been deleted from dev/test/prod by Will. I'm not sure @lkmorlan needed to make a drush command, if it was already done. 

I _did_ have the test tables on my localhost, but that must be because I had loaded the database that Craig sent us -- that must have been an older DB where the test tables were still in.

@NicoledeGreef, @chrislaick , it is unfortuntate that the tables are already deleted, as it means the backup PVC that is almost full is not going to be resolved by this. I have created [issue #498](https://github.com/bcgov/MFIN-Data-Catalogue/issues/498) to deal with this problem.

**Closed as completed** 2024-06-11 22:29 UTC
Labels: task, Sprint 17, Sprint 18
