### ISSUE TITLE
Search not returning relevant results

### ISSUE THREAD

**Issue by ChristaBull** [bcgov/MFIN-Data-Catalogue#153] opened 2023-09-07 20:13 UTC
**OP timer**

---

## Describe the bug
Some search terms don't find/return results that are visible when there's no search term that appear to be relevant

## To reproduce
Steps to reproduce the behaviour:
1. Go to https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/
2. Enter "grant" into the search
3. Click **Search**

## Expected behaviour
The Home Owner Grant Dashboard appears in the search results

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/141185297/804434a9-8501-4df1-9904-09843f3033c4)

## Screenshots
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/141185297/bc568248-5cb6-4e9d-b1fd-8268fe382966)

**Comment by ChristaBull** [comment] 2023-09-07 21:47
I just realized I get a 500 error when trying to open the HOG Dashboard item, which may be related to why it's not returned when a search term is provided.

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/141185297/c53aff48-c538-4220-a201-eb0a2c12f4ba)

**Comment by NicoledeGreef** [comment] 2023-09-08 16:08
Thanks for the report @ChristaBull!  There were some issues with importing values discussed in relation to #150. Perhaps that lead to the item being corrupted.

**Comment by CraigClark** [comment] 2023-09-12 15:21
closing this. The internal server error is fixed with #154.

Search is working fine, the issue is that it isn't being indexed on a schedule. We need to set up cron to do that. A task for this has been created at #164

**Closed as completed by CraigClark** 2023-09-12 15:21 UTC
Labels: bug, Sprint 6, task
