### ISSUE TITLE
Put gcNotify in production mode on prod

### ISSUE THREAD

**Issue by CraigClark** [bcgov/MFIN-Data-Catalogue#307] opened 2024-01-08 14:22 UTC
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5809902792

---

GCNotify is currently running in teams mode. This is for testing. It needs to be put into production mode.

Before this can happen, #306, #308 and #199 need to be resolved

## DoD

- [x] #306
- [x] #308 
- [x] #199 
- [x] test and dev in teams mode and (drupal admin)
- [x] prod on prod mode (drupal admin)

**Comment by CraigClark** [comment] 2024-01-16 21:19
done

**Comment by NicoledeGreef** [comment] 2024-05-13 23:17
Current state:
@NicoledeGreef @CraigClark @lkmorlan are the contacts -->this will need an update to include other Ministry staff

The process to go to Production appears to be:
![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/bbcb03f4-871c-4294-90bd-c268008a398d)

Recent messages logged indicate that they were generated with the "dv21 team" API key. The messages, however, are coming from dv14, dev, and test.  @NicoledeGreef logged into Prod and Bookmarked a few MRs to see if changes would trigger messages from that environment.

**Comment by NicoledeGreef** [comment] 2024-05-16 18:32
Flipping to Production will generate new keys and the keys need to be put into the secrets vault.

**Comment by NicoledeGreef** [comment] 2024-05-21 23:21
~~@NicoledeGreef to use Lansweeper to file a service request ticket with App Ops.~~
this comment was made on the wrong ticket. see #[43](https://github.com/bcgov/MFIN-Data-Catalogue/issues/43#issuecomment-2133882044) instead

**Comment by NicoledeGreef** [comment] 2024-05-22 23:00
![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/a98b1028-fc75-4c84-86c1-9a244d999ae6)

**Comment by CraigClark** [comment] 2024-05-23 19:05
@NicoledeGreef 

I'll pass this back to your team. Here is what needs to happen.

## Prevent test and dev from ever sending messages to users
- [ ] in the test and dev environments remove the prod key from the vault.

## Make sure prod is always in production mode
- [ ] add this line to _settings.php_ on the prod environment `$config['message_gcnotify.settings']['mode'] = 2;`

## Document this configuration
- [x] Document config in the wiki with explanation @CraigClark

**Comment by CraigClark** [comment] 2024-05-23 20:01
See documentation at https://github.com/bcgov/MFIN-Data-Catalogue/wiki/GCNotify-config

**Comment by NicoledeGreef** [comment] 2024-05-27 17:47
Note: this is a "to do" after the build. Moved to "To Do" status and it will be re-assigned to devs.

**Comment by danhgov** [comment] 2024-05-30 23:16
@lkmorlan, I was assigned this today, but I don't think I'm currently equipped to complete it.

- in the [Message GC Notify settings](https://cat.data.fin.gov.bc.ca/admin/config/message/message-gcnotify), all of the _API Key_ and _Template ID_ fields (on prod/test/dev) contain only the string "key".
- the docs at https://github.com/bcgov/MFIN-Data-Catalogue/wiki/GCNotify-config say we should store these keys in the Vault -- to which I currently do **not** have access. I'm not sure if they are already in there, or how to get them out.
- in the docs for the [Message GC Notify module](https://www.drupal.org/project/message_gcnotify) (which I see you are the primary maintainer of -- very cool!), it sounds as though this module works in concert with the message, message_subscribe, and message_notify modules... But none of those are installed on the data-catalogue site.

Can you help me out here a little bit? I'm not sure where to start.

**Comment by lkmorlan** [comment] 2024-05-31 14:52
On a Drupal config page, the config you see is the value that is saved in the database. However, this value can be overridden in `settings.php`, which gets the value from the vault. The values are already there. You can see the value that is actually used by running `drush config-get --include-overridden`.

The only part of `message_gcnotify` that we are using is the code that interacts with the GC Notify API. This module was written to be used with the other `message` modules but this part can be used on its own.

**Comment by danhgov** [comment] 2024-05-31 17:06
Thanks, @lkmorlan, that is very helpful. I'm not quite there yet, though, and need a bit more help.

`settings.php` appears to _only_ set the 'test' and 'team' api keys, even on the prod server:
```
# GCNotify
$config['message_gcnotify.settings']['test_apikey'] = getenv('GCNOTIFY_TEST_APIKEY');
$config['message_gcnotify.settings']['team_apikey'] = getenv('GCNOTIFY_TEAM_APIKEY');
$config['message_gcnotify.settings']['test_template'] = getenv('GCNOTIFY_TEST_TEMPLATE');
```
`drush config-get --include-overridden` is a handy command that I didn't know about - thank you! Running it on the prod server, it looks to me as though the production keys are not in place:

```
/var/www/html $ drush config-get --include-overridden  message_gcnotify.settings
_core:
  default_config_hash: RFpONvnSH8Y8NdP8EFbIOlUkEwRb6a0DA1qgQIxDz9w
enabled: true
mode: 1
debug_mode: false
baseurl: 'https://api.notification.canada.ca/'
prod_apikey: key
prod_template: key
test_apikey: gcntfy-dv21_test-932276...XXXXX...65f10203b8
team_apikey: gcntfy-dv21_team-932276...XXXXX...76654e2f1e
test_template: 20638...XXXXX...d8332
```
What am I missing here?

**Comment by danhgov** [comment] 2024-05-31 17:23
Also, I'm trying to send myself a test email from the "Test" server, and I can't get it to work:

- In Teams mode, I get this error: `GC Notify error 400: BadRequestError: You cannot send to these recipients because you used a team and safelist API key.` I'm not sure what that means.
- In Test mode, it appears to work, but the email hasn't arrived during 5 or more minutes I've been waiting. I tried one to my gov.bc.ca email, and one to my gmail account. Neither have come through. I ran cron a couple times right after sending, in case that is part of it.

**Comment by lkmorlan** [comment] 2024-05-31 17:29
@danhgov the production API key need to be added to `settings.php` and perhaps also to the vault.

When in team mode, you can only send to members of the team. You are probably not a member. That needs to be configured on GC Notify.

In test mode, it will pretend to work, but will not actually send the email.

**Comment by danhgov** [comment] 2024-06-06 00:08
This is working now. To make it happen, here is what I did:

- Created a new production API key at https://notification.canada.ca
- Got @chrislaick to add it to the Vault
- Asked Chris to also clone the 'gcnotify-test-template' item in the vault to an equivalent 'prod' item. 
  - (We are re-using the same template for both. All they are is the BC-Gov logo preceding the _body_ portion of the email.)
- Added these two lines to `values-mfin-data-catalogue-prod.yaml` in the tenant-gitops repo:
  - ![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/130506582/2766030e-a997-425b-b365-3509d8f5e92c)
- Switched it to 'Production' mode at https://cat.data.fin.gov.bc.ca/admin/config/message/message-gcnotify
  - Note that @lkmorlan set this to be _ignored_ from Drupal config, so a git commit is not necessary to capture this change.
- Tested by
  - Creating a test metadata-record
  - Bookmarking it, with my normal 'dan.howard@gov.bc.ca' email address
    - Note that this address is in the safe-send list, for testing the GC Notify service.   
  - Creating a dummy user, whose email address is my gmail address.
    - Bookmarking it for this user, too.
    - Note that _this_ address is _not_ in the safe-send list, for testing the GC Notify service.  
  - Submitting a "Major edit (notify subscribers)" for my test metadata-record
  - verifying that the notification email was sent to _both_ of these addresses

**Comment by danhgov** [comment] 2024-06-11 22:30
@NicoledeGreef, I had set this ticket to "ready for review". If you are aware that people are getting the messages that they should be, then this ticket can be closed.

**Comment by NicoledeGreef** [comment] 2024-06-11 23:14
Confirmed that Production is notifying users as expected:

![Image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/5d9d65bf-4131-4204-98b6-0216e71e3758)

Thanks @danhgov!

**Closed as completed by NicoledeGreef** 2024-06-11 23:14 UTC
Labels: Priority: high, task, Sprint 17, Sprint 18
