### ISSUE TITLE
"Data sets used" exclusion needed

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#205] opened 2023-10-23 22:08 UTC
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5436892581

---
Currently, when an editor is adding values to "Data sets used", the auto-complete includes the record that is being edited.  This should ideally be excluded.

To replicate: 

1. Edit Metadata record "Home Owner Grant Dashboard"
2. scroll down to "Assets used" (formerly "Data sets used")
3. type "home" and matches appear but the Dashboard itself should not be able to reference itself

![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/f52a146c-5c9e-4c3d-ad56-e93cc6f67109)

**Comment by lkmorlan** [comment] 2023-10-30 18:45
Drupal core feature request to create a setting that does this:
https://www.drupal.org/project/drupal/issues/2280479

**Comment by CraigClark** [comment] 2023-11-01 20:53
@lkmorlan Lets do this with a view and a contextual filter to get rid of the node the user is editing

**Comment by lkmorlan** [comment] 2023-11-02 14:18
I implemented this using the default value "Content ID from URL". The View preview works, but when editing a content item, no items auto-complete. It is as if it is getting a empty default value. Pausing for now.

**Comment by CraigClark** [comment] 2023-11-14 18:37
I have a newer branch for this fix here, https://github.com/bcgov/MFIN-Data-Catalogue/tree/205-exclude-current-node-in-data-sets-used

however it isn't working. 

The problem seems to be when auto complete is used with a views entity reference.

After adding an entity reference to the view, I an able to filter out the current node. If I uses checboxes as the field formatter, I do not see the current node as an option. View preview with contextual filter works as well. However, when I switch formatter to autocomplete, I get no results. 

There are others reporting this problem

https://www.drupal.org/project/drupal/issues/3021342

https://www.drupal.org/project/social/issues/3257193

**Comment by CraigClark** [comment] 2023-11-14 18:41
We can look for patches, but if we can't find one, we might have to live with this issue until an upate comes out. I imagine being able to use auto-complete is more important than filtering out the current node

**Comment by NicoledeGreef** [comment] 2024-02-12 19:50
relates to #348

**Comment by CraigClark** [comment] 2024-02-15 19:50
#360 is a duplicate of this

**Comment by CraigClark** [comment] 2024-03-19 19:27
@lkmorlan 

I met with Joel on this. This looks like an upstream issue. Could you please track it down ad submit a fix for it?

**Comment by CraigClark** [comment] 2024-03-19 19:32
@lkmorlan 

I did this with a contextual filter on a view, then used an entity reference field to the view. This is the way this should work. Works like a charm with every input method except auto-complete. Unfortunately, auto-complete is the only viable option for this field.

**Comment by lkmorlan** [comment] 2024-03-22 16:15
I have fixed this by updating and using the core patch:

https://www.drupal.org/project/drupal/issues/2280479#comment-15510177

**Comment by lkmorlan** [comment] 2024-03-22 16:44
The fix is in branch [205-patch-core-exclude-self-reference](/bcgov/MFIN-Data-Catalogue/tree/205-patch-core-exclude-self-reference).

**Comment by CraigClark** [comment] 2024-03-22 19:01
Tested and approved on dv14 @lkmorlan good to merge

**Comment by lkmorlan** [comment] 2024-03-22 19:27
Merged

**Closed as completed by lkmorlan** 2024-03-22 19:27 UTC
Labels: Priority: low, Sprint 8, Sprint 9, stuck, task, Sprint 13, Sprint 14, Sprint 15
