### ISSUE TITLE
504 Gateway Time-outs occurring in Delivery

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/MFIN-Data-Catalogue#154] opened 2023-09-07 21:21 UTC
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5126008433

---

## Describe the bug
Noticed during demo in Delivery: 

"504 Gateway Time-out
The server didn't respond in time."

## To reproduce
Steps to reproduce the behaviour:
1. Login in to Delivery: https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/
2. Click on a metadata record that has a number of revisions: https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/node/13
3. Click Revisions tab: https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/node/13/revisions
4. Using the radio buttons select two revisions from the list and click the button "Compare selected revisions"
5. Results in timeout

## Expected behaviour
Diffs would be successfully displayed.

## Screenshots
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/e6fec988-cba0-4988-bcd3-2024b249029d)
![image](https://github.com/bcgov/MFIN-Data-Catalogue/assets/26335003/f78bb65f-d82f-48cb-8e6f-260922d714fc)

**Comment by CraigClark** [comment] 2023-09-11 13:12
This appears to be caused by an error in a custom formatter. 

> Error: Call to a member function id() on null in Drupal\bc_dc\Plugin\Field\FieldFormatter\FacetSearchLinkFieldFormatter->viewElements() (line 55 of /var/www/html/modules/custom/bc_dc/src/Plugin/Field/FieldFormatter/FacetSearchLinkFieldFormatter.php).

To duplicate the error:

1. go to [node/44](https://mfin-data-catalogue.apps.silver.devops.gov.bc.ca/node/44)
2. see that there is a 500 error
3. go to the logs
4. filter in php errors
5. see the reported error

**Comment by lkmorlan** [comment] 2023-09-11 20:12
These are two separate issues. The issue identified by @CraigClark on Sep. 11 is fixed in the above commit.
The original issue is a timeout because it takes a long time to generate the diff. The timeout duration should be increased.

**Comment by CraigClark** [comment] 2023-09-20 16:14
Will has increased the limits in the OpenShift environment. I am still gettting 504 on the node where I am trying to do a diff on a data set that has 100 data dictionary rows. This is edge case enough we will open another ticket if real data sets actually hit this limit

**Closed as completed by CraigClark** 2023-09-20 16:14 UTC
Labels: bug, Sprint 6, task

**Comment by CraigClark** [comment] 2023-09-20 16:16
Update: I was able to run the diff on the huge data set previously mentioned. In addition to Will changing limits, the environment is now on php 8.1, not sure if that's related
